version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - libsnappy-dev
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py