FONT_NAME_MAP = {
    "AcademyEngravedLetPlain": "Academy Engraved LET",
    "AmericanTypewriter": "American Typewriter",
    "AndaleMono": "Andale Mono",
    "Apple-Chancery": "Apple Chancery",
    "Arial-Black": "Arial Black",
    "Arial-BoldItalicMT": "Arial",
    "ArialMT": "Arial",
    "ArialNarrow": "Arial Narrow",
    "ArialRoundedMTBold": "Arial Rounded MT Bold",
    "ArialUnicodeMS": "Arial Unicode MS",
    "Avenir-Book": "Avenir",
    "AvenirNext-Regular": "Avenir Next",
    "AvenirNextCondensed-Regular": "Avenir Next Condensed",
    "Baskerville": "Baskerville",
    "BigCaslon-Medium": "Big Caslon",
    "BodoniSvtyTwoITCTT-Book": "Bodoni 72",
    "BodoniSvtyTwoOSITCTT-Book": "Bodoni 72 Oldstyle",
    "BodoniSvtyTwoSCITCTT-Book": "Bodoni 72 Smallcaps",
    "BradleyHandITCTT-Bold": "Bradley Hand",
    "BrushScriptMT": "Brush Script MT",
    "Calibri": "Calibri",
    "Cambria": "Cambria",
    "CanelaText-Regular": "Canela Text",
    "Chalkboard": "Chalkboard",
    "ChalkboardSE-Regular": "Chalkboard SE",
    "Chalkduster": "Chalkduster",
    "Charter-Roman": "Charter",
    "Cochin": "Cochin",
    "ComicSansMS": "Comic Sans MS",
    "Copperplate": "Copperplate",
    "CourierNewPSMT": "Courier New",
    "DINAlternate-Bold": "DIN Alternate",
    "DINCondensed-Bold": "DIN Condensed",
    "Didot": "Didot",
    "FoundersGrotesk-Regular": "Founders Grotesk",
    "Futura-Medium": "Futura",
    "Geneva": "Geneva",
    "Georgia": "Georgia",
    "GillSans": "Gill Sans",
    "HelveticaNeue": "Helvetica Neue",
    "HelveticaNeue-Bold": "Helvetica Neue",
    "HelveticaNeue-Light": "Helvetica Neue",
    "HelveticaNeue-Medium": "Helvetica Neue",
    "Herculanum": "Herculanum",
    "HoeflerText-Regular": "Hoefler Text",
    "Impact": "Impact",
    "LucidaGrande": "Lucida Grande",
    "Luminari-Regular": "Luminari",
    "MarkerFelt-Thin": "Marker Felt",
    "Menlo-Regular": "Menlo",
    "MicrosoftSansSerif": "Microsoft Sans Serif",
    "Monaco": "Monaco",
    "Noteworthy-Light": "Noteworthy",
    "Optima-Regular": "Optima",
    "Palatino-Roman": "Palatino",
    "Papyrus": "Papyrus",
    "PartyLetPlain": "Party LET",
    "Phosphate-Inline": "Phosphate",
    "ProximaNova-Regular": "Proxima Nova",
    "Rockwell-Regular": "Rockwell",
    "STIXGeneral-Regular": "STIXGeneral",
    "STIXTwoMath-Regular": "STIX Two Math",
    "STIXTwoText": "STIX Two Text",
    "SavoyeLetPlain": "Savoye LET",
    "SignPainter-HouseScript": "SignPainter",
    "Skia-Regular": "Skia",
    "SnellRoundhand": "Snell Roundhand",
    "Tahoma": "Tahoma",
    "TimesNewRomanPSMT": "Times New Roman",
    "Trattatello": "Trattatello",
    "TrebuchetMS": "Trebuchet MS",
    "Verdana": "Verdana",
    "Zapfino": "Zapfino",
}
