name: Build README

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

    jobs:
      job1:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt-get -y install libsnappy-dev
          pip install poetry
          poetry install --with docs
      - name: Built README with Sphinx
        run: |
          poetry run sphinx-build -q -b markdown -t MarkdownDocs docs docs/build docs/index.rst
      - name: Check in new README
        run: |
          cp docs/build/index.md README.md
          if ! git diff-index --quiet HEAD; then
            echo Committing
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m 'Updating README' README.md
          fi
          echo Done
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true