name: Deploy Sphinx documentation to Pages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install the project
        run: uv sync --locked --all-extras --dev --group docs

      - name: Build and deploy Sphinx documentation
        uses: sphinx-notes/pages@v3
        with:
          sphinx_build_options: -t HtmlDocs 

      # - id: deployment
      # uses: sphinx-notes/pages@v3
      # with:
      #   sphinx_build_options: -t HtmlDocs 
